{% set name = "vowpalwabbit" %}
{% set version = "9.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/VowpalWabbit/vowpal_wabbit/archive/refs/tags/{{ version }}.tar.gz
    sha256: 50c0a766c3f0f4a4ba29ac1db8949ee352e0d7e4f2df819fb410f8a34e3ea051
    patches:
      - turn_off_sse2_flags.diff  # [osx and (build_platform != target_platform)]

build:
  number: 0
  skip: true  # [win]
  script:
     - cp $BUILD_PREFIX/share/gnuconfig/config.* .
     - export CMAKE_ARGS="$CMAKE_ARGS -DRAPIDJSON_SYS_DEP=On"
     - export CMAKE_ARGS="$CMAKE_ARGS -DFMT_SYS_DEP=On"
     - export CMAKE_ARGS="$CMAKE_ARGS -DSPDLOG_SYS_DEP=On"
     - export CMAKE_ARGS="$CMAKE_ARGS -DBUILD_FLATBUFFERS=On"
     - {{ PYTHON }} setup.py --cmake-options=$(echo $CMAKE_ARGS | sed 's/ /;/g') install

requirements:
  build:
    - gnuconfig  # [unix]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - flatbuffers                            # [build_platform != target_platform]
    - rapidjson                              # [build_platform != target_platform]
    - fmt                                    # [build_platform != target_platform]
    - spdlog                                 # [build_platform != target_platform]
    - zlib                                   # [build_platform != target_platform]
    - cmake >=3.13
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - boost
    - boost-cpp
    - tox
    - zlib
    - flatbuffers
    - rapidjson
    - fmt
    - spdlog

  run:
    - python
    - boost
    - boost-cpp
    - fmt
    - zlib

test:
  imports:
    - vowpalwabbit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/VowpalWabbit/vowpal_wabbit
  summary: Vowpal Wabbit Python package
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jackgerrits
    - gramhagen
    - peterychang
    - xhochy
    - ngam
