{% set name = "vowpalwabbit" %}
{% set version = "9.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/VowpalWabbit/vowpal_wabbit/archive/refs/tags/{{ version }}.tar.gz
  sha256: 46d206c5b2336ed0c9dc228d34457db4acd9e3ade8b509f8fb426183651984c1
  patches:
    - 0001-Use-system-dependencies.patch
    - 0002-Apply-CMAKE_ARGS-if-set.patch
    - 0003-system-ensmallen-and-armadillo.patch
    - 0004-Make-build-verbose.patch

build:
  number: 0
  skip: true  # [win or py<36]
  script:
    - {{ PYTHON }} -m pip install . -v --no-deps --no-build-isolation
  ignore_run_exports:
    # spdlog is used in header only mode.
    # See https://github.com/VowpalWabbit/vowpal_wabbit/blob/9.9.0/ext_libs/ext_libs.cmake#L23.
    - spdlog
    # Armadillo is used in header only mode
    - armadillo

requirements:
  build:
    - cmake >=3.13
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch  # [not win]
    - m2-patch  # [win]
  host:
    - pip
    - python
    - libboost {{ boost }}
    - py-boost {{ boost }}
    - zlib {{ zlib }}
    - spdlog >=1.9.2
    - rapidjson  >=1.1.0
    - fmt >=8.1.1
    - eigen >=3.4.0
    - armadillo
    - ensmallen
    - sse2neon  # [arm64 or aarch64 or ppc64le]
    - setuptools
    - wheel
  run:
    - python
    - zlib
    - rapidjson
    - fmt
    - py-boost

test:
  source_files:
    - python
    - test
  imports:
    - vowpalwabbit
  commands:
    - pip check
    - python -m pytest -v python/tests/ -k "not test_ccb_and_automl"
  requires:
    - pip
    - pytest
    - pandas
    - numpy
    - scipy
    - scikit-learn

about:
  home: https://vowpalwabbit.org/
  summary: Vowpal Wabbit is a machine learning system which pushes the frontier of machine learning with techniques such as online, hashing, allreduce, reductions, learning2search, active, and interactive learning.
  description: |
    Vowpal Wabbit is a machine learning system which pushes the frontier of machine learning with
    techniques such as online, hashing, allreduce, reductions, learning2search, active, and interactive
    learning. There is a specific focus on reinforcement learning with several contextual bandit
    algorithms implemented and the online nature lending to the problem well. Vowpal Wabbit is a
    destination for implementing and maturing state of the art algorithms with performance in mind.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/VowpalWabbit/vowpal_wabbit
  doc_url: https://vowpalwabbit.org/docs/vowpal_wabbit/python/latest/index.html

extra:
  recipe-maintainers:
    - jackgerrits
    - gramhagen
    - xhochy
    - ngam
    - byronxu99
